/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { WorkerProfileExtraSkill } from "./WorkerProfileExtraSkill";
import { WorkerProfileExtraSkillCountArgs } from "./WorkerProfileExtraSkillCountArgs";
import { WorkerProfileExtraSkillFindManyArgs } from "./WorkerProfileExtraSkillFindManyArgs";
import { WorkerProfileExtraSkillFindUniqueArgs } from "./WorkerProfileExtraSkillFindUniqueArgs";
import { DeleteWorkerProfileExtraSkillArgs } from "./DeleteWorkerProfileExtraSkillArgs";
import { WorkerProfileExtraSkillService } from "../workerProfileExtraSkill.service";
@graphql.Resolver(() => WorkerProfileExtraSkill)
export class WorkerProfileExtraSkillResolverBase {
  constructor(protected readonly service: WorkerProfileExtraSkillService) {}

  async _workerProfileExtraSkillsMeta(
    @graphql.Args() args: WorkerProfileExtraSkillCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [WorkerProfileExtraSkill])
  async workerProfileExtraSkills(
    @graphql.Args() args: WorkerProfileExtraSkillFindManyArgs
  ): Promise<WorkerProfileExtraSkill[]> {
    return this.service.workerProfileExtraSkills(args);
  }

  @graphql.Query(() => WorkerProfileExtraSkill, { nullable: true })
  async workerProfileExtraSkill(
    @graphql.Args() args: WorkerProfileExtraSkillFindUniqueArgs
  ): Promise<WorkerProfileExtraSkill | null> {
    const result = await this.service.workerProfileExtraSkill(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => WorkerProfileExtraSkill)
  async deleteWorkerProfileExtraSkill(
    @graphql.Args() args: DeleteWorkerProfileExtraSkillArgs
  ): Promise<WorkerProfileExtraSkill | null> {
    try {
      return await this.service.deleteWorkerProfileExtraSkill(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
