/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  WorkerProfileExtraSkill as PrismaWorkerProfileExtraSkill,
} from "@prisma/client";

export class WorkerProfileExtraSkillServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.WorkerProfileExtraSkillCountArgs, "select">
  ): Promise<number> {
    return this.prisma.workerProfileExtraSkill.count(args);
  }

  async workerProfileExtraSkills(
    args: Prisma.WorkerProfileExtraSkillFindManyArgs
  ): Promise<PrismaWorkerProfileExtraSkill[]> {
    return this.prisma.workerProfileExtraSkill.findMany(args);
  }
  async workerProfileExtraSkill(
    args: Prisma.WorkerProfileExtraSkillFindUniqueArgs
  ): Promise<PrismaWorkerProfileExtraSkill | null> {
    return this.prisma.workerProfileExtraSkill.findUnique(args);
  }
  async createWorkerProfileExtraSkill(
    args: Prisma.WorkerProfileExtraSkillCreateArgs
  ): Promise<PrismaWorkerProfileExtraSkill> {
    return this.prisma.workerProfileExtraSkill.create(args);
  }
  async updateWorkerProfileExtraSkill(
    args: Prisma.WorkerProfileExtraSkillUpdateArgs
  ): Promise<PrismaWorkerProfileExtraSkill> {
    return this.prisma.workerProfileExtraSkill.update(args);
  }
  async deleteWorkerProfileExtraSkill(
    args: Prisma.WorkerProfileExtraSkillDeleteArgs
  ): Promise<PrismaWorkerProfileExtraSkill> {
    return this.prisma.workerProfileExtraSkill.delete(args);
  }
}
