/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { WorkerProfileSkill } from "./WorkerProfileSkill";
import { WorkerProfileSkillCountArgs } from "./WorkerProfileSkillCountArgs";
import { WorkerProfileSkillFindManyArgs } from "./WorkerProfileSkillFindManyArgs";
import { WorkerProfileSkillFindUniqueArgs } from "./WorkerProfileSkillFindUniqueArgs";
import { DeleteWorkerProfileSkillArgs } from "./DeleteWorkerProfileSkillArgs";
import { WorkerProfileSkillService } from "../workerProfileSkill.service";
@graphql.Resolver(() => WorkerProfileSkill)
export class WorkerProfileSkillResolverBase {
  constructor(protected readonly service: WorkerProfileSkillService) {}

  async _workerProfileSkillsMeta(
    @graphql.Args() args: WorkerProfileSkillCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [WorkerProfileSkill])
  async workerProfileSkills(
    @graphql.Args() args: WorkerProfileSkillFindManyArgs
  ): Promise<WorkerProfileSkill[]> {
    return this.service.workerProfileSkills(args);
  }

  @graphql.Query(() => WorkerProfileSkill, { nullable: true })
  async workerProfileSkill(
    @graphql.Args() args: WorkerProfileSkillFindUniqueArgs
  ): Promise<WorkerProfileSkill | null> {
    const result = await this.service.workerProfileSkill(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => WorkerProfileSkill)
  async deleteWorkerProfileSkill(
    @graphql.Args() args: DeleteWorkerProfileSkillArgs
  ): Promise<WorkerProfileSkill | null> {
    try {
      return await this.service.deleteWorkerProfileSkill(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
