/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { WorkerProfile } from "./WorkerProfile";
import { WorkerProfileCountArgs } from "./WorkerProfileCountArgs";
import { WorkerProfileFindManyArgs } from "./WorkerProfileFindManyArgs";
import { WorkerProfileFindUniqueArgs } from "./WorkerProfileFindUniqueArgs";
import { DeleteWorkerProfileArgs } from "./DeleteWorkerProfileArgs";
import { WorkerProfileService } from "../workerProfile.service";
@graphql.Resolver(() => WorkerProfile)
export class WorkerProfileResolverBase {
  constructor(protected readonly service: WorkerProfileService) {}

  async _workerProfilesMeta(
    @graphql.Args() args: WorkerProfileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [WorkerProfile])
  async workerProfiles(
    @graphql.Args() args: WorkerProfileFindManyArgs
  ): Promise<WorkerProfile[]> {
    return this.service.workerProfiles(args);
  }

  @graphql.Query(() => WorkerProfile, { nullable: true })
  async workerProfile(
    @graphql.Args() args: WorkerProfileFindUniqueArgs
  ): Promise<WorkerProfile | null> {
    const result = await this.service.workerProfile(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => WorkerProfile)
  async deleteWorkerProfile(
    @graphql.Args() args: DeleteWorkerProfileArgs
  ): Promise<WorkerProfile | null> {
    try {
      return await this.service.deleteWorkerProfile(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
