/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  JobPostingExtraSkill as PrismaJobPostingExtraSkill,
} from "@prisma/client";

export class JobPostingExtraSkillServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.JobPostingExtraSkillCountArgs, "select">
  ): Promise<number> {
    return this.prisma.jobPostingExtraSkill.count(args);
  }

  async jobPostingExtraSkills(
    args: Prisma.JobPostingExtraSkillFindManyArgs
  ): Promise<PrismaJobPostingExtraSkill[]> {
    return this.prisma.jobPostingExtraSkill.findMany(args);
  }
  async jobPostingExtraSkill(
    args: Prisma.JobPostingExtraSkillFindUniqueArgs
  ): Promise<PrismaJobPostingExtraSkill | null> {
    return this.prisma.jobPostingExtraSkill.findUnique(args);
  }
  async createJobPostingExtraSkill(
    args: Prisma.JobPostingExtraSkillCreateArgs
  ): Promise<PrismaJobPostingExtraSkill> {
    return this.prisma.jobPostingExtraSkill.create(args);
  }
  async updateJobPostingExtraSkill(
    args: Prisma.JobPostingExtraSkillUpdateArgs
  ): Promise<PrismaJobPostingExtraSkill> {
    return this.prisma.jobPostingExtraSkill.update(args);
  }
  async deleteJobPostingExtraSkill(
    args: Prisma.JobPostingExtraSkillDeleteArgs
  ): Promise<PrismaJobPostingExtraSkill> {
    return this.prisma.jobPostingExtraSkill.delete(args);
  }
}
