/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { JobPosting } from "./JobPosting";
import { JobPostingCountArgs } from "./JobPostingCountArgs";
import { JobPostingFindManyArgs } from "./JobPostingFindManyArgs";
import { JobPostingFindUniqueArgs } from "./JobPostingFindUniqueArgs";
import { DeleteJobPostingArgs } from "./DeleteJobPostingArgs";
import { JobPostingService } from "../jobPosting.service";
@graphql.Resolver(() => JobPosting)
export class JobPostingResolverBase {
  constructor(protected readonly service: JobPostingService) {}

  async _jobPostingsMeta(
    @graphql.Args() args: JobPostingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [JobPosting])
  async jobPostings(
    @graphql.Args() args: JobPostingFindManyArgs
  ): Promise<JobPosting[]> {
    return this.service.jobPostings(args);
  }

  @graphql.Query(() => JobPosting, { nullable: true })
  async jobPosting(
    @graphql.Args() args: JobPostingFindUniqueArgs
  ): Promise<JobPosting | null> {
    const result = await this.service.jobPosting(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => JobPosting)
  async deleteJobPosting(
    @graphql.Args() args: DeleteJobPostingArgs
  ): Promise<JobPosting | null> {
    try {
      return await this.service.deleteJobPosting(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
